### ISSUE TITLE
Api: Users

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/API-Users-RIKA-WIN23#2]
- [ ] EC-rika-project/dummie-repo#58
- [ ] EC-rika-project/dummie-repo#109
- [ ] EC-rika-project/dummie-repo#110
- [ ] EC-rika-project/dummie-repo#111
- [ ] EC-rika-project/dummie-repo#112
- [ ] EC-rika-project/dummie-repo#113
- [ ] EC-rika-project/dummie-repo#114
- [ ] EC-rika-project/dummie-repo#115
