### ISSUE TITLE
Api-Users:  sätt upp projekt och grundstruktur

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/API-Users-RIKA-WIN23#3]
**OBS!**
*Nedan tasks gäller bara för att sätta upp boiler plate kod och att skapa filer samt styra upp dependency injection.*
*Undantaget är baserepository som bör vara en "abstract" klass som tar emot TEntity och utför CRUD mot databasen.*

**Tasks:**

*Classes*
- [x] Api-Users-Task: Sätt upp dto och entity för:

- Users (ex:  UserEntity : IdentityUser - UserDto)
- UserProfiles (ex: UserProfileEntity - UserProfileDto)
- Addresses
- UserPaymentMethods
- UserWishList
- UserShoppingCart
- ShoppingCartItem

*Context*
- [x] Skapa DBContext med alla entiteter med hjälp av Entity framework Core.
- [x] Lägg till Connectionstring till databas.

**APIControllers**
*De första 2 controllers här är exempel på vad som bör ingå, att lägga till de bör göras i Featuren API:Users och dess UserStories (task)
**OBS ALLA ENDPOINTS SKA VARA UPSÄKRADE MED APINYCKLAR OCH SKA ANVÄNDA SWAGGER**

- [x] Api-Users-Task: Sätt upp en UserController.
Som exempel kan följande endpoints finnas:
- Get(id) - Hämtar en användare baserat på Id. Som användare använder man sitt eget id, som admin väljer man vilket id.
- Get(email) - Hämtar en användare baserat på email. Endast för admin.
- Get - Hämtar Alla användare - Endast för admin.
- Post - För att skapa en ny användare. (Ska även skapa och koppla en ny tom UserProfileEntity till UserEntity)
- Put(id) - För att upddatera en användare. Som användare använder man sitt eget id, som admin väljer man vilket id.
- Delete(id) -För att radera en användarer Användare. Som användare använder man sitt eget id, som admin väljer man vilket id.

- [x] Api-Users-Task: Sätt upp en UserProfileController:
*Som exempel kan följande endpoints finnas:*
- Get(id) - Hämtar en user profile baserat på Id. Som användare använder man sitt eget id, som admin väljer man vilket id.
- Post - För att skapa en ny user profile (Bör skapas i samband med att man skapar ny user, men bra att ha om något går fel) - Endast för admin.
- Put(id) - För att uppdaterar en user profile. Som användare använder man sitt eget id, som admin väljer man vilket id.
- Delete(id) - För att radera (tömma på innehåll - ska inte tas bort) en user profile. Som användare använder man sitt eget id, som admin väljer man vilket id.

- [x] Api-Users-Task: Sätt upp en AddressesController.
- [ ] Api-Users-Task: Sätt upp en UserWishListController.
- [ ] Api-Users-Task: Sätt upp en UserShoppingCartController.
- [ ] Api-Users-Task: Sätt upp en ShoppingCartItemController.

**Services**
- [ ] Api-Users-Task: Sätt upp Services för följande:
- User
- UserProfile
- Address
- UserPaymentMethods
- UserWishList
- UserShoppingCart
- ShoppingCartItem

**Repositories**
- [x] Api-Users-Task: Sätt upp ett BaseRepository med CRUD mot SQL databas.
- [x] Api-Users-Task: Sätt upp Repositories för följande:
- User
- UserProfile
- Address
- UserPaymentMethods
- UserWishList
- UserShoppingCart
- ShoppingCartItem

**Program.cs**
- [x] Api-Users-Task: Konfigurera Program.cs med Controllers, rätt middleware och Services, Repositories för att kunna köra dependency injection och Identity/ annan Auttentiseringslösning, CORS mm.

**Definition Of Done**
- [x] Alla Dto:er och entiter är uppsatta.
- [x] En DbContext är skapad.
- [x] Connectionstring till db finns.
- [ ] Alla Controllers är uppsatta.
- [ ] Alla Services är uppsatta.
- [x] BaseRepository är uppsatt.
- [x] Alla andra Repositories är uppsatta.
- [x] Program.cs är konfigurerad.
- [ ] API går att använda med rätt nyckel och behörighet från godkända addresser med CORS.
- [x] Users som INTE är administratörer kommer endast åt egen data.
- [x] Users som är administratörer kommer åt all data de är behöriga till.

**Test Case Scenario**
Vi testar samma funktion 2 ggr med lyckat och misslyckat resultat.
Förutsättningar: Klasser och Interfaces finns.
Vad kan vi testa?
-*Enhetstester:*
Separata metoder i controllers, services och repositories.
-*Integrationstester:*
Mellan klientappar och API samt API och databas.

- [x] Testa att Logga in en användare som har skickat in email och lösenord till API. 

Skapa och anropa en metod som loggar in användare och skicka in SignInDto som parameter. T.ex: var result = LoginUserAsync_ShouldLogInUser_AndReturnUserDto();

- Arrange
1.Skapa en SignInDto med Email, Lösenord och RememberMe.
2. Sätt upp ett förväntat resultat i variabeln expectedResult.
3. Ställ in vad metoden ska ta emot och returnera genom den mockade servicen

- Act
1. Anropa metoden i den mockade servicen och spara resultatet i en variabel: result. 

- Assert
Säkerställ att resultaten i result och expectedResult är lika.

- [x] Testa att Logga in en användare som har skickat in fel email och fel lösenord till API. 
- Arrange
1. Sätt upp en användare i en SignInDto med email, lösenord och rememberMe.
2. Sätt upp ett felmeddelande med ResponseResult som expectedResult.
3. Ställ in vad metoden ska ta emot och returnera genom den mockade servicen.

- Act
Anropa SignInUserAsync i den mockade servicen och spara resultatet i en variabel: result. 

- Assert
Säkerställ att resultaten i result och expectedResult är lika.
Samt att expectedResult.Message, result.Message stämmer överens.

- [x] Testa att spara en ny användarprofil till databasen där allt fungerar.
- Arrange
1. Skapa en SignUpDto med Email, FirstName och LastName.
2. Spara in förväntat resultat i variabeln expectedResult (ResponsFactory.Created(message).
3. Ställ in vad metoden ska ta emot och returnera genom den mockade servicen.

- Act
Anropa CreateUserProfileAsynci den mockade servicen och spara resultatet i en variabel: result. 

- Assert
Säkerställ att resultaten i result och expectedResult är lika.
Samt att expectedResult.Message, result.Message stämmer överens.

__________________________________________________________________________________________________________________________________
- [x] Testa att spara en ny användarprofil till databasen där åldern anges som negativt tal.
- Arrange
1. Sätt upp en mock för UserDto med användarId, användarnamn, emailadress.
2. Sätt upp en mock för UserProfileDto med ålder och ange en negativ ålder..
3. Sätt upp en UserProfileEntity och mappa in Dto'erna till entiteten.

- Act
1. Skapa och anropa en metod som sparar en användare till databasen och skicka in UserProfileEntity som en parameter. T.ex: var result = SaveUserProfileAsync_ShouldNotSaveUserProfile_AndReturnError();

- Assert
1. Säkerställ att användaren inte sparas korrekt i databasen.
2. Kolla att felet som returneras inte beskriver vilken property som är felaktig.

- [x] Testa en factory som lyckas att omvandla från UserDto till UserEntity.
- Arrange
1. Skapa en UserDto med följande properties: Id, Email, IsExternal, AddressId.
2. Sätt upp en metod som tar in en UserDto som parameter och returnerar en UserEntity. T.ex: 
Create_ShouldCastUserDtoToUserEntity_AndReturnUserEntity(UserDto);

- Act
1. Anropa metoden och spara ner i en variable: result.

- Assert
1. Jämför properties i result mot properties i UserDto så att allting är identiskt.

- [x] Testa att uppdatera en användares adress med lyckat resultat.
- Arrange
1. Skapa en AddressDto med följande properties: UserId, StreetName, StreetNumber, ApartmentNumber, PostalCode, City, Country.
2. Sätt upp en metod som tar in en AddressDto som parameter och returnerar en uppdaterad AddressEntity. T.ex: 
Update_ShouldUpdateAddressEntity_AndReturnAddressEntity(AddressDto);

- Act
1. Anropa metoden och spara ner i en variable: result.

- Assert
1. Kontrollera att result != null. 
2. Jämför properties i result mot properties AddressDto så att allting är identiskt.
