### ISSUE TITLE
Api-Users: Som en klient (AdminApp) vill jag kunna uppdatera alla existerande användare som jag har behörighet till.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/API-Users-RIKA-WIN23#7]
**Tasks:**
- [ ] Api-Users-Task: Skapa endpoint för att uppdatera användare baserat på id. [HttpPut]
- [ ] Api-Users-Task: Skapa endpoint för att uppdatera användare baserat på email. [HttpPut]

- [ ] Api-Users-Task:  Implementera logik för repository, service och controller.
- [ ] Api-Users-Task: Validera att användaren finns innan uppdatering.
- [ ] Api-Users-Task: Bekräftelsemeddelande vid lyckad updatering.
- [ ] Api-Users-Task: Felmeddelanden om uppdateringen misslyckas.

**Definition Of Done:**

- Användaren uppdateras korrekt i databasen.
- API returnerar statuskod 200 OK vid lyckad uppdatering
- API returnerar statuskod 404 Not Found om användaren inte hittas med id.
- API returnerar staturkod 500 Internal Server Error som catch vid oväntade fel.
