### ISSUE TITLE
Api-Users: Som en klient (WebApp) vill jag kunna uppdatera den inloggade användaren och få bekräftelse på uppdateringen.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/API-Users-RIKA-WIN23#8]
**Tasks:**
- [x] Api-Users-Task: Skapa endpoint för att uppdatera sin egen användare baserat på id. [HttpPut]
- [x] Api-Users-Task:  Implementera logik för repository, service och controller.
- [x] Api-Users-Task: Validera att användaren finns innan uppdatering.
- [x] Api-Users-Task: Bekräftelsemeddelande vid lyckad updatering.
- [x] Api-Users-Task: Felmeddelanden om uppdateringen misslyckas.
 

**Definition Of Done:**

- Användaren uppdateras korrekt i databasen.
- API returnerar statuskod 200 OK vid lyckad uppdatering
- API returnerar statuskod 404 Not Found om användaren inte hittas med id.
- API returnerar staturkod 500 Internal Server Error som catch vid oväntade fel.
